### ISSUE TITLE
How to get the certificate of completion?

### ISSUE THREAD

**Issue by preeti13456** [londonappbrewery/Flutter-Course-Resources#14]

**Comment by Austin-Godwin** [comment]
I hope the photo explains it all

**Comment by harishpadmanabh-HP** [comment]
after you complete the course you can find a green cup icon above in top right . You can get certificate from that

**Comment by preeti13456** [comment]
@harishpadmanabh-HP  Can you please send a visual for that because i can't find any green cup though I have completed full course.
![2020-04-26 (3)](https://user-images.githubusercontent.com/36129347/80300385-d9bd9000-87b9-11ea-8941-085669ba1e7d.png)
