### ISSUE TITLE
Section6 Video2 code Confusion

### ISSUE THREAD

**Issue by yueli96** [londonappbrewery/Flutter-Course-Resources#23]
Thanks for the amazing lecture. When I was watching Section 6 Hot Reload and Hot Restart, the sample code suddenly changed from using stateless widget to stateful widget after a few slides, which is kind of confusing. What is the difference between those two and when should we use them?

**Comment by dev-aentgs** [comment]
Stateful widgets are commonly used when building apps and part of apps with **anything that can change** ( anything that can have a state, it can be ui change or data change or any other).
For example displaying data that can change with time on the UI.

Stateless widgets are commonly used when for parts of the app that **do not change over time**.
For example app can have the AppBar in a stateless widget and the body in a stateful widget.

Along the course, it will be clear ahead.
