### ISSUE TITLE
Flutter doctor

### ISSUE THREAD

**Issue by kelvin002a** [londonappbrewery/Flutter-Course-Resources#24]
**Unable to locate a development device; run 'flutter doctor'
I have run flutter doctor on terminal and it says Android sdk file not found 
Pls help me __
![Uploading IMG_20200603_174033.jpg…]()**

**Comment by dsoldo** [comment]
@kelvin002a  you have to install SDK Platform (File->Settings then search for SDK and install required Version).... However my advice to you is to use Visual Studio Code instead of Android Studio (if you are on the beggining of your journey, :) - happy coding

**Comment by kelvin002a** [comment]
Exception: Gradle task assembleDebug failed ) exit code 1
