### ISSUE TITLE
mi_card_flutter issue

### ISSUE THREAD

**Issue by prakhargupta496** [londonappbrewery/Flutter-Course-Resources#26]
![IMG_20200615_121632](https://user-images.githubusercontent.com/54628037/84626711-3b20f600-af03-11ea-8d19-0d5fcce4644b.jpg)
I am getting this error when I try to get dependencies.

**Comment by subhangpati** [comment]
Hey, its an issue with the server you both need to bother about that.

**Comment by sajjadtalib29** [comment]
**After clicking on get dependencies if you still shows up the error get dependencies.
You need to just close the android studio and restart it.**

**Comment by prakhargupta496** [comment]
This issue is a issue due to network problem. Get a good network and the problem will be solved.
