### ISSUE TITLE
13. Flutter State Management - Step 1 - Stub Project doesn't exist

### ISSUE THREAD

**Issue by jaredbaszler** [londonappbrewery/Flutter-Course-Resources#3]
In the course resource main page the link for the stub projet in the final module (13. Flutter State Management) points to the completed project, not the stub project.

**Comment by TheMuellenator** [comment]
The Todoey app is started from scratch as per the course lessons.

**Comment by gupta-shrinath** [comment]
@jaredbaszler I know this is old but I have added it in my pull request to this repo check it out.
 https://github.com/gupta-shrinath/Flutter-Course-Resources
