### ISSUE TITLE
I am getting this issue, and I have no idea how this will be resolved.

### ISSUE THREAD

**Issue by ajeetkumar955** [londonappbrewery/Flutter-Course-Resources#48]
Invalid depfile: C:\Users\Ajeet Chaurasia\AndroidStudioProjects\my_card\.dart_tool\flutter_build\2c96f7b7ab065ed1d5c4586aab33f984\kernel_snapshot.d

Screenshot: https://screenrec.com/share/meFCf8rk9h

**Comment by prateek-aher** [comment]
@ajeetkumar955 
This happens when you're trying to run a mobile app but have web imports in your file. Remove `import 'dart : html';` from your `main.dart` file. This will fix it.

**Comment by prateek-aher** [comment]
@ajeetkumar955 
This happens when you're trying to run a mobile app but have web imports in your file. Remove `import 'dart : html';` from your `main.dart` file. This will fix it.

**Comment by ajeetkumar955** [comment]
Thanks, it is fixed as of now but I did the same to resolve it.

**Comment by prateek-aher** [comment]
@ajeetkumar955 close the issue if fixed.

**Comment by kienghuynh** [comment]
> @ajeetkumar955 This happens when you're trying to run a mobile app but have web imports in your file. Remove `import 'dart:html';` from your `main.dart` file. This will fix it.

oh god it too easy but i spend 3 day on research.
thank you very much =)))
