### ISSUE TITLE
Android SDK didn't got installed as checked in flutter doctor. 

### ISSUE THREAD

**Issue by Shhabs** [londonappbrewery/Flutter-Course-Resources#5]
![Capture](https://user-images.githubusercontent.com/54140596/68811605-e42e0800-0625-11ea-9627-3a5dc2e62b54.PNG)

**Comment by Shhabs** [comment]
Can someone please help me ?

**Comment by eduxsolano** [comment]
The console tells you the instructions . Run command flutter doctor - - android-licenses and install vs code extension in provided link
