### ISSUE TITLE
Section 16's 218 introducing the provider package demo is missing from download

### ISSUE THREAD

**Issue by SeasonLeee** [londonappbrewery/Flutter-Course-Resources#6]
Hi there, first of all thanks for the awesome course!

But as the title stated, the demo Angela was using to demonstrate the topic was missing from download, and... will it be listed? Hope it will, and I'm pretty sure that Angela was saying we can download it from the resource listed in here, I think. 

Anyway, thanks!😊

**Comment by gupta-shrinath** [comment]
Please checkout this pull request created by me.
Check out https://github.com/gupta-shrinath/Flutter-Course-Resources

**Comment by SeasonLeee** [comment]
@gupta-shrinath thanks, but I've completed the course now, but thanks anyway

**Comment by gupta-shrinath** [comment]
:+1:
