### ISSUE TITLE
Couldn't access the documentation

### ISSUE THREAD

**Issue by bugrameral** [londonappbrewery/Flutter-Course-Resources#62]
When trying to access documentation, I'm having Your connection isn't private or 404 error. Have tried with different computers. Does anyone have the same issue?

Thanks

**Comment by Ankit-10409** [comment]
It is because the documentation moved to https://api.flutter.dev/flutter/ but hasn't been updated here, you can just go to this link and search for whatever you want to.

**Comment by Boltgsmooth** [comment]
Thank you very much
